
name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install --location=global @angular/cli
      - run: npm install --location=global npm
      - run: npm install --legacy-peer-deps
      - run: npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
